[General]
SyntaxVersion=2
BeginHotkey=67
BeginHotkeyMod=4
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=34fef51a-4b94-4426-ae95-2c71a187f6ed
Description=adtClean
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
MouseWheel -9999
    MoveTo 245, 23
LeftClick 1
 MoveTo 245, 180
 LeftClick 1

KeyPress "Enter", 1
